_commit: f489e26
_src_path: /home/lightningralf/ai-society/softwareco/tpl-owned-repo/
core_owner_handle: '@lightningralf'
org_owner_handle: '@lightningralf'
owned_owner_handle: '@lightningralf'
repo_slug: dspx


