[project]
name = "dspycodexexec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "dspy-ai>=3.0.2",
    "duckduckgo-search>=8.1.1",
    "httpx>=0.28.1",
    "mlflow>=2.18.0",
    "pandas>=2.3.2",
]
