# summary: "Binds the concept_coverage GEPA wrapper program to its source candidate by hash and verifies that binding before consumption."
# read_when:
#   - "Changing the concept_coverage wrapper template, the optimizer-manifest metric_honesty block, or how consumers verify it."
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Mapping, Sequence

CONCEPT_COVERAGE_METRIC = "concept_coverage"
CONCEPT_COVERAGE_PROGRAM_NAME = "concept_coverage_program.py"
METRIC_HONESTY_FIELD = "metric_honesty"
METRIC_HONESTY_KEYS = frozenset(
    {"metric", "wrapper_program_sha256", "source_program_sha256", "criteria_sha256"}
)
_CANDIDATE_HASH_BINDING_PREFIX = "CANDIDATE_PROGRAM_SHA256 = "


class MetricHonestyError(ValueError):
    """Raised when the concept_coverage wrapper is not verifiably bound to its source."""


_CONCEPT_COVERAGE_PROGRAM_TEMPLATE = '''# summary: "GEPA metric wrapper binding the candidate program to its intent's concept-coverage criteria."
"""Generated by dspx program_refinement_gepa for one bounded GEPA attempt.

The wrapper re-exports the candidate program and adds a ``normalize_output``
hook that projects gold/pred onto a concept-coverage verdict, so DSPx's
``exact`` optimizer metric scores 1.0 only when every declared quality
criterion for the output field passes on the prediction. Feedback names the
missing concept groups instead of demanding a verbatim example answer.

The wrapper is bound to one exact source program by SHA-256: loading refuses
any candidate whose bytes drifted from ``CANDIDATE_PROGRAM_SHA256``.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import sys
from pathlib import Path

from dspx.services.program_quality_evaluation import (
    evaluate_declared_quality,
    normalize_quality_criteria,
)

CANDIDATE_PROGRAM_PATH = Path(__CANDIDATE_PROGRAM_PATH__)
CANDIDATE_PROGRAM_SHA256 = __CANDIDATE_PROGRAM_SHA256__
QUALITY_CRITERIA = json.loads(__QUALITY_CRITERIA_JSON__)
OUTPUT_FIELDS = json.loads(__OUTPUT_FIELDS_JSON__)


def _load_candidate():
    """Import the candidate like optimize_service does, without leaking modules."""

    actual_sha256 = hashlib.sha256(CANDIDATE_PROGRAM_PATH.read_bytes()).hexdigest()
    if actual_sha256 != CANDIDATE_PROGRAM_SHA256:
        raise RuntimeError(
            "candidate program hash drifted from the concept_coverage wrapper binding: "
            f"{CANDIDATE_PROGRAM_PATH}"
        )
    candidate_dir = str(CANDIDATE_PROGRAM_PATH.parent)
    spec = importlib.util.spec_from_file_location("program", CANDIDATE_PROGRAM_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot import candidate program {CANDIDATE_PROGRAM_PATH}")
    sibling_names = [
        path.stem
        for path in CANDIDATE_PROGRAM_PATH.parent.glob("*.py")
        if path.stem != CANDIDATE_PROGRAM_PATH.stem
    ]
    previous = {name: sys.modules.get(name) for name in [spec.name, *sibling_names]}
    inserted = candidate_dir not in sys.path
    if inserted:
        sys.path.insert(0, candidate_dir)
    module = importlib.util.module_from_spec(spec)
    # Evict cached namesakes first: generated programs import generic sibling names.
    for name in sibling_names:
        sys.modules.pop(name, None)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    finally:
        for name, earlier in previous.items():
            if earlier is None:
                sys.modules.pop(name, None)
            else:
                sys.modules[name] = earlier
        if inserted:
            try:
                sys.path.remove(candidate_dir)
            except ValueError:
                pass
    return module


_CANDIDATE = _load_candidate()
_NORMALIZED_CRITERIA = normalize_quality_criteria(QUALITY_CRITERIA, outputs=OUTPUT_FIELDS)


def build_student(*args, **kwargs):
    return _CANDIDATE.build_student(*args, **kwargs)


def io_spec():
    io_spec_fn = getattr(_CANDIDATE, "io_spec", None)
    if callable(io_spec_fn):
        return io_spec_fn()
    return {"inputs": [], "outputs": list(OUTPUT_FIELDS)}


def output_weights():
    weights_fn = getattr(_CANDIDATE, "output_weights", None)
    if callable(weights_fn):
        return weights_fn()
    return {field: 1.0 for field in OUTPUT_FIELDS}


def concept_coverage_verdict(key: str, pred: str) -> tuple[str, str]:
    """Return (expected verdict, observed verdict) for one output field."""

    criteria = [item for item in _NORMALIZED_CRITERIA if item["output_field"] == key]
    if not criteria:
        raise KeyError(key)
    ids = ",".join(str(item["id"]) for item in criteria)
    expected = f"concept_coverage[{ids}]:passed"
    evaluation = evaluate_declared_quality(criteria, {key: pred})
    if evaluation["status"] == "passed":
        return expected, expected
    detail = "; ".join(
        f"{row['id']}: matched {row['required_groups_matched']}/"
        f"{row['required_groups_total']} groups, missing group indexes "
        f"{row['missing_group_indexes']}, forbidden hits {row['forbidden_hits']}, "
        f"missing_output {row['missing_output']}"
        for row in evaluation["criteria"]
    )
    return expected, f"concept_coverage[{ids}]:failed ({detail})"


def normalize_output(key, gold, pred, pred_name=None, pred_trace=None):
    try:
        return concept_coverage_verdict(str(key), str(pred))
    except KeyError:
        delegate = getattr(_CANDIDATE, "normalize_output", None)
        if callable(delegate):
            return delegate(key, gold, pred, pred_name, pred_trace)
        return gold, pred
'''


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def criteria_sha256(criteria: Sequence[Mapping[str, Any]]) -> str:
    """Hash the declared quality criteria exactly as the GEPA proposal binding does."""

    return sha256_bytes(
        json.dumps(
            [dict(item) for item in criteria],
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    )


def render_concept_coverage_program(
    *,
    candidate_program: Path,
    candidate_program_sha256: str,
    criteria: Sequence[Mapping[str, Any]],
    output_fields: Sequence[str],
) -> str:
    """Render the deterministic wrapper bound to one source program by path and hash."""

    return (
        _CONCEPT_COVERAGE_PROGRAM_TEMPLATE.replace(
            "__CANDIDATE_PROGRAM_PATH__", repr(str(candidate_program))
        )
        .replace("__CANDIDATE_PROGRAM_SHA256__", repr(str(candidate_program_sha256)))
        .replace(
            "__QUALITY_CRITERIA_JSON__",
            repr(
                json.dumps(
                    [dict(item) for item in criteria],
                    ensure_ascii=False,
                    sort_keys=True,
                )
            ),
        )
        .replace("__OUTPUT_FIELDS_JSON__", repr(json.dumps(list(output_fields))))
    )


def metric_honesty_block(
    *,
    wrapper_program_sha256: str,
    source_program_sha256: str,
    criteria_digest: str,
) -> dict[str, str]:
    """Build the closed metric_honesty block recorded in the optimizer manifest."""

    return {
        "metric": CONCEPT_COVERAGE_METRIC,
        "wrapper_program_sha256": str(wrapper_program_sha256),
        "source_program_sha256": str(source_program_sha256),
        "criteria_sha256": str(criteria_digest),
    }


def _hex_digest(value: object, *, label: str) -> str:
    text = str(value or "").strip()
    if len(text) != 64 or any(ch not in "0123456789abcdef" for ch in text):
        raise MetricHonestyError(f"metric_honesty {label} must be a sha256 hex digest")
    return text


def validate_metric_honesty_block(value: object) -> dict[str, str]:
    """Validate the closed shape of a metric_honesty block without consulting files."""

    if not isinstance(value, Mapping):
        raise MetricHonestyError("metric_honesty must be an object")
    value = {str(key): item for key, item in value.items()}
    if set(value) != METRIC_HONESTY_KEYS:
        raise MetricHonestyError(
            "metric_honesty must contain exactly metric, wrapper_program_sha256, "
            "source_program_sha256, criteria_sha256"
        )
    if value.get("metric") != CONCEPT_COVERAGE_METRIC:
        raise MetricHonestyError(
            f"metric_honesty metric must be {CONCEPT_COVERAGE_METRIC}"
        )
    return {
        "metric": CONCEPT_COVERAGE_METRIC,
        "wrapper_program_sha256": _hex_digest(
            value.get("wrapper_program_sha256"), label="wrapper_program_sha256"
        ),
        "source_program_sha256": _hex_digest(
            value.get("source_program_sha256"), label="source_program_sha256"
        ),
        "criteria_sha256": _hex_digest(
            value.get("criteria_sha256"), label="criteria_sha256"
        ),
    }


def wrapper_binding_line(candidate_program_sha256: str) -> str:
    return f"{_CANDIDATE_HASH_BINDING_PREFIX}{str(candidate_program_sha256)!r}"


def verify_concept_coverage_metric_honesty(
    *,
    optimizer_manifest: Mapping[str, Any],
    source_program_sha256: str,
    optimizer_root: Path | None = None,
    source_program_path: Path | None = None,
    criteria: Sequence[Mapping[str, Any]] | None = None,
    output_fields: Sequence[str] | None = None,
) -> dict[str, str]:
    """Verify that the optimizer's program is the wrapper bound to the source candidate.

    Hash-level checks always run: the block is closed, the wrapper hash equals the
    manifest program hash, and the recorded source hash equals the current source
    program hash. When the source program path, criteria, and output fields are
    supplied (the materialization path), the wrapper is re-derived byte-for-byte
    from the source program and criteria and compared with the wrapper the
    optimizer actually consumed.
    """

    block = validate_metric_honesty_block(optimizer_manifest.get(METRIC_HONESTY_FIELD))
    program = optimizer_manifest.get("program")
    manifest_program_hash = (
        str(program.get("sha256") or "").strip() if isinstance(program, Mapping) else ""
    )
    if block["wrapper_program_sha256"] != manifest_program_hash:
        raise MetricHonestyError(
            "metric_honesty wrapper_program_sha256 does not match the GEPA optimizer "
            "manifest program hash"
        )
    if block["source_program_sha256"] != source_program_sha256:
        raise MetricHonestyError(
            "metric_honesty source_program_sha256 does not match source candidate"
        )
    if criteria is not None and block["criteria_sha256"] != criteria_sha256(criteria):
        raise MetricHonestyError(
            "metric_honesty criteria_sha256 does not match intent quality_criteria"
        )
    if source_program_path is None or criteria is None or output_fields is None:
        return block
    if optimizer_root is None:
        raise MetricHonestyError(
            "metric_honesty wrapper re-derivation requires the optimizer output root"
        )
    source_program_path = source_program_path.expanduser().resolve()
    if sha256_file(source_program_path) != source_program_sha256:
        raise MetricHonestyError(
            "source candidate program hash changed during metric_honesty verification"
        )
    expected_text = render_concept_coverage_program(
        candidate_program=source_program_path,
        candidate_program_sha256=source_program_sha256,
        criteria=criteria,
        output_fields=output_fields,
    )
    expected_bytes = expected_text.encode("utf-8")
    if sha256_bytes(expected_bytes) != block["wrapper_program_sha256"]:
        raise MetricHonestyError(
            "metric_honesty wrapper_program_sha256 does not match the wrapper "
            "re-derived from the source program and intent criteria"
        )
    wrapper_path = (
        optimizer_root.expanduser().resolve()
        / "source"
        / (CONCEPT_COVERAGE_PROGRAM_NAME)
    )
    try:
        actual_bytes = wrapper_path.read_bytes()
    except OSError as exc:
        raise MetricHonestyError(
            f"concept_coverage wrapper program is missing from optimizer output: {wrapper_path}"
        ) from exc
    if actual_bytes != expected_bytes:
        raise MetricHonestyError(
            "concept_coverage wrapper bytes differ from the wrapper re-derived from "
            "the source program and intent criteria"
        )
    binding_line = wrapper_binding_line(source_program_sha256)
    if binding_line not in expected_text.splitlines():
        raise MetricHonestyError(
            "concept_coverage wrapper does not carry the source program hash binding"
        )
    return block
