# summary: "Exports the public module-synthesis contracts and runtime operations."
# read_when:
#   - "Changing the supported import surface for dspx.synthesis consumers."

from .contracts import (
    CandidateArtifact,
    CandidateRecord,
    CandidateWorkspace,
    EvaluationRecord,
    ModuleFieldIR,
    ModuleSpecIR,
    PromotionDecision,
    PromotionShell,
    SelectionPolicy,
    StrategyRecord,
    SynthesisBundle,
    SynthesisRequest,
    build_module_candidate_record,
    build_module_evaluation_record,
    build_module_promotion_decision,
    build_module_promotion_shell,
    build_module_selection_policy,
    build_module_strategy_record,
    build_module_synthesis_bundle,
    build_module_synthesis_request,
    module_spec_to_ir,
)
from .runtime import (
    evaluate_module_synthesis_bundle,
    execute_module_synthesis_bundle,
    materialize_module_candidate_workspace,
    materialize_module_synthesis_bundle,
    module_synthesis_run_summary,
    promote_selected_module_candidate,
    synthesis_workspace_dir,
)

__all__ = [
    "CandidateArtifact",
    "CandidateRecord",
    "CandidateWorkspace",
    "EvaluationRecord",
    "ModuleFieldIR",
    "ModuleSpecIR",
    "PromotionDecision",
    "PromotionShell",
    "SelectionPolicy",
    "StrategyRecord",
    "SynthesisBundle",
    "SynthesisRequest",
    "build_module_candidate_record",
    "build_module_evaluation_record",
    "build_module_promotion_decision",
    "build_module_promotion_shell",
    "build_module_selection_policy",
    "build_module_strategy_record",
    "build_module_synthesis_bundle",
    "build_module_synthesis_request",
    "evaluate_module_synthesis_bundle",
    "execute_module_synthesis_bundle",
    "materialize_module_candidate_workspace",
    "materialize_module_synthesis_bundle",
    "module_spec_to_ir",
    "module_synthesis_run_summary",
    "promote_selected_module_candidate",
    "synthesis_workspace_dir",
]
